import { Plus, UserPlus, Copy, Check, ArrowLeft, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";
import GroupMembers from "./GroupMembers";

interface FamilyGroup {
  id: string;
  name: string;
  created_by: string;
  member_count: number;
  is_head: boolean;
}

interface FamilyManagementProps {
  onBack?: () => void;
}

export default function FamilyManagement({ onBack }: FamilyManagementProps) {
  const { user } = useAuth();
  const [myGroups, setMyGroups] = useState<FamilyGroup[]>([]);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [joinDialogOpen, setJoinDialogOpen] = useState(false);
  const [newGroupName, setNewGroupName] = useState("");
  const [inviteCode, setInviteCode] = useState("");
  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [isJoining, setIsJoining] = useState(false);
  const [selectedGroup, setSelectedGroup] = useState<{ id: string; name: string } | null>(null);

  useEffect(() => {
    fetchMyGroups();
  }, [user]);

  const fetchMyGroups = async () => {
    if (!user) return;

    try {
      // Get all family groups the user is a member of
      const { data: memberships, error: membershipError } = await supabase
        .from("family_members")
        .select("family_group_id, is_head")
        .eq("user_id", user.id);

      if (membershipError) throw membershipError;

      if (!memberships || memberships.length === 0) {
        setMyGroups([]);
        return;
      }

      const groupIds = memberships.map((m) => m.family_group_id);

      // Get group details
      const { data: groups, error: groupsError } = await supabase.from("family_groups").select("*").in("id", groupIds);

      if (groupsError) throw groupsError;

      // Get member count for each group
      const groupsWithCount = await Promise.all(
        (groups || []).map(async (group) => {
          const { count } = await supabase
            .from("family_members")
            .select("*", { count: "exact", head: true })
            .eq("family_group_id", group.id);

          const membership = memberships.find((m) => m.family_group_id === group.id);

          return {
            ...group,
            member_count: count || 0,
            is_head: membership?.is_head || false,
          };
        }),
      );

      setMyGroups(groupsWithCount);
    } catch (error: any) {
      console.error("Error fetching groups:", error);
      toast.error("그룹 정보를 불러오는데 실패했습니다");
    }
  };

  const handleCreateGroup = async () => {
    if (!user || !newGroupName.trim()) {
      toast.error("그룹 이름을 입력해주세요");
      return;
    }

    setIsCreating(true);
    try {
      // Create family group (invite_code will be auto-generated by trigger)
      const { data: newGroup, error: groupError } = await supabase
        .from("family_groups")
        .insert([
          {
            name: newGroupName.trim(),
            created_by: user.id,
          },
        ] as any)
        .select("*")
        .single();

      if (groupError) throw groupError;

      // Add creator as a member and set as head
      const { error: memberError } = await supabase.from("family_members").insert({
        family_group_id: newGroup.id,
        user_id: user.id,
        is_head: true,
      });

      if (memberError) throw memberError;

      toast.success("그룹이 생성되었습니다!");

      setNewGroupName("");
      setCreateDialogOpen(false);
      fetchMyGroups();
    } catch (error: any) {
      console.error("Error creating group:", error);
      toast.error("그룹 생성에 실패했습니다");
    } finally {
      setIsCreating(false);
    }
  };

  const handleJoinGroup = async () => {
    if (!user || !inviteCode.trim()) {
      toast.error("초대 코드를 입력해주세요");
      return;
    }

    setIsJoining(true);
    try {
      // Find group by name (temporary until invite_code is added)
      const { data: group, error: groupError } = await supabase
        .from("family_groups")
        .select("*")
        .eq("name", inviteCode.trim())
        .maybeSingle();

      if (groupError) {
        console.error("Error finding group:", groupError);
        toast.error("그룹 조회 중 오류가 발생했습니다");
        return;
      }

      if (!group) {
        toast.error("유효하지 않은 초대 코드입니다");
        return;
      }

      // Check if already a member
      const { data: existingMember } = await supabase
        .from("family_members")
        .select("*")
        .eq("family_group_id", group.id)
        .eq("user_id", user.id)
        .single();

      if (existingMember) {
        toast.error("이미 참여한 그룹입니다");
        return;
      }

      // Add as member
      const { error: memberError } = await supabase.from("family_members").insert({
        family_group_id: group.id,
        user_id: user.id,
      });

      if (memberError) throw memberError;

      toast.success(`"${group.name}" 그룹에 참여했습니다!`);
      setInviteCode("");
      setJoinDialogOpen(false);
      fetchMyGroups();
    } catch (error: any) {
      console.error("Error joining group:", error);
      toast.error("그룹 참여에 실패했습니다");
    } finally {
      setIsJoining(false);
    }
  };

  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCode(code);
    toast.success("초대 코드가 복사되었습니다");
    setTimeout(() => setCopiedCode(null), 2000);
  };

  if (selectedGroup) {
    return (
      <GroupMembers groupId={selectedGroup.id} groupName={selectedGroup.name} onBack={() => setSelectedGroup(null)} />
    );
  }

  return (
    <div className="flex flex-col min-h-screen pb-24 bg-gradient-to-br from-background via-background to-secondary/30 px-4">
      <section className="pt-8 max-w-2xl mx-auto w-full">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-4">
            {onBack && (
              <Button variant="ghost" size="icon" onClick={onBack} className="flex-shrink-0">
                <ArrowLeft size={24} />
              </Button>
            )}
            <h2 className="text-senior-2xl font-bold text-secondary-foreground">그룹 관리</h2>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="grid grid-cols-2 gap-3 mb-8">
          <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
            <DialogTrigger asChild>
              <Button size="xl" className="w-full">
                <Plus size={24} />
                가족 만들기
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-md">
              <DialogHeader>
                <DialogTitle className="text-senior-xl">새 그룹 만들기</DialogTitle>
                <DialogDescription className="text-senior-base">그룹 이름을 입력해주세요</DialogDescription>
              </DialogHeader>
              <div className="space-y-4 pt-4">
                <div className="space-y-2">
                  <Label htmlFor="group-name" className="text-senior-lg">
                    그룹 이름
                  </Label>
                  <Input
                    id="group-name"
                    placeholder="예: 우리 가족"
                    className="h-14 text-senior-base px-4"
                    value={newGroupName}
                    onChange={(e) => setNewGroupName(e.target.value)}
                  />
                </div>
                <Button
                  size="xl"
                  onClick={handleCreateGroup}
                  disabled={isCreating || !newGroupName.trim()}
                  className="w-full"
                >
                  {isCreating ? "생성 중..." : "그룹 만들기"}
                </Button>
              </div>
            </DialogContent>
          </Dialog>

          <Dialog open={joinDialogOpen} onOpenChange={setJoinDialogOpen}>
            <DialogTrigger asChild>
              <Button size="xl" variant="outline" className="w-full">
                <UserPlus size={24} />
                가족 참여
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-md">
              <DialogHeader>
                <DialogTitle className="text-senior-xl">그룹 참여하기</DialogTitle>
                <DialogDescription className="text-senior-base">초대 코드를 입력해주세요</DialogDescription>
              </DialogHeader>
              <div className="space-y-4 pt-4">
                <div className="space-y-2">
                  <Label htmlFor="invite-code" className="text-senior-lg">
                    초대 코드
                  </Label>
                  <Input
                    id="invite-code"
                    placeholder="예: ABC123"
                    className="h-14 text-senior-base px-4 uppercase"
                    value={inviteCode}
                    onChange={(e) => setInviteCode(e.target.value.toUpperCase())}
                    maxLength={6}
                  />
                </div>
                <Button
                  size="xl"
                  onClick={handleJoinGroup}
                  disabled={isJoining || !inviteCode.trim()}
                  className="w-full"
                >
                  {isJoining ? "참여 중..." : "그룹 참여하기"}
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        </div>

        {/* My Groups */}
        <div className="space-y-4">
          <h3 className="text-senior-xl font-bold text-secondary-foreground">내 그룹 ({myGroups.length})</h3>

          {myGroups.length === 0 ? (
            <Card className="p-8 text-center">
              <p className="text-senior-base text-muted-foreground mb-2">아직 그룹이 없어요</p>
              <p className="text-senior-sm text-muted-foreground">새 그룹을 만들거나 초대 코드로 참여해보세요</p>
            </Card>
          ) : (
            <div className="space-y-3">
              {myGroups.map((group) => (
                <Card key={group.id} className="p-6">
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <h4 className="text-senior-lg font-bold mb-1">{group.name}</h4>
                      <p className="text-senior-sm text-muted-foreground">구성원 {group.member_count}명</p>
                    </div>
                    <div className="flex gap-2">
                      {group.is_head && (
                        <span className="text-senior-xs bg-accent/10 text-accent px-3 py-1 rounded-full flex items-center gap-1">
                          👑 가장
                        </span>
                      )}
                      {group.created_by === user?.id && (
                        <span className="text-senior-xs bg-primary/10 text-primary px-3 py-1 rounded-full">
                          내가 만듦
                        </span>
                      )}
                    </div>
                  </div>

                  <div className="flex items-center gap-2 bg-secondary/30 rounded-lg p-3 mb-3">
                    <div className="flex-1">
                      <p className="text-senior-xs text-muted-foreground mb-1">그룹 멤버</p>
                      <p className="text-senior-xl font-bold">{group.member_count}명</p>
                    </div>
                  </div>

                  <Button
                    variant="outline"
                    size="lg"
                    onClick={() => setSelectedGroup({ id: group.id, name: group.name })}
                    className="w-full gap-2"
                  >
                    <Users size={20} />
                    구성원 보기
                  </Button>
                </Card>
              ))}
            </div>
          )}
        </div>
      </section>
    </div>
  );
}
